elasticity_vc_mapped_fault_abl.so: ../../../src/rp/rpn2_vc_elasticity_mapped_fault_abl.f90 ../../../src/rp/rpt2_vc_elasticity_mapped_fault_abl.f90
	f2py -c ../../../src/rp/rpn2_vc_elasticity_mapped_fault_abl.f90 ../../../src/rp/rpt2_vc_elasticity_mapped_fault_abl.f90 -m elasticity_vc_mapped_fault_abl
